module.exports = {
    rules: {
        semi: ['error', 'always'],
        curly: ['error'],
        eqeqeq: ['error'],
        'no-plusplus': ['error'],
        'max-depth': ['error', 4],
        camelcase: ['error', { properties: 'never' }],
        'no-array-constructor': ['error'],
        'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
        'no-multiple-empty-lines': ['error', { max: 2 }],
        'no-spaced-func': ['error'],
        'no-trailing-spaces': ['error'],
        'semi-spacing': ['error', { before: false, after: true }],
        'no-loop-func': ['error'],
        'no-magic-numbers': ['error', { ignore: [0, 1, 2] }],
        'no-redeclare': ['error'],
        'no-unused-expressions': ['error'],
        'no-use-before-define': ['error'],
        yoda: ['error'],
        'no-undef': ['error'],
        'no-irregular-whitespace': ['error'],
        'no-constant-condition': ['error', { checkLoops: false }],
        'no-unused-vars': ['error', {
            argsIgnorePattern: '^_',
            varsIgnorePattern: '^_',
        }],
        'eol-last': ['error', 'always'],
        'comma-dangle': ['error', 'always-multiline'],
    },
    env: {
        es6: true,
    },
    extends: ['eslint:recommended'],
};
